# k8s/service-workflow/deployment-worker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-service-worker
  namespace: default
  labels:
    app: workflow-service
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-service
      component: worker
  template:
    metadata:
      labels:
        app: workflow-service
        component: worker
    spec:
      containers:
      - name: workflow-service
        image: airat139/service-workflow:1
        args: ["worker"]
        ports:
        - containerPort: 3000
        env:
        - name: TEMPORAL_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: workflow-config
              key: TEMPORAL_ADDRESS
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: workflow-config
              key: PORT
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"