apiVersion: v1
kind: Secret
metadata:
  name: telegram-secret
type: Opaque
data:
  TELEGRAM_BOT_TOKEN:  NzQ3ODA1NzI1MTpBQUVzRzdRdGxCdDdSc3ZpZ0xxOWpOMHFaM3NUdElGeUdwbw== # base64 encoded
  TELEGRAM_CHAT_ID: NjU0OTU4NDIz # base64 encoded
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-communications
  labels:
    app: service-communications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-communications
  template:
    metadata:
      labels:
        app: service-communications
    spec:
      containers:
        - name: service-communications
          image: airat139/mail-poller:4
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKERS
              value: "kafka:9092"
            - name: KAFKA_TOPIC
              value: "workflow-events"
            - name: GATEWAY_HOST
              value: service-gateway
            - name: GATEWAY_PORT
              value: "50051"
            - name: MAILHOG_HOST
              value: mailhog
            - name: MAILHOG_PORT
              value: "8025"
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-secret
                  key: TELEGRAM_BOT_TOKEN
            - name: TELEGRAM_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: telegram-secret
                  key: TELEGRAM_CHAT_ID
            - name: LOG_LEVEL
              value: info
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: service_communications
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m" 