// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/gateway.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMessageRequest) Reset() {
	*x = NewMessageRequest{}
	mi := &file_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMessageRequest) ProtoMessage() {}

func (x *NewMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMessageRequest.ProtoReflect.Descriptor instead.
func (*NewMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *NewMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *NewMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NewMessageRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *NewMessageRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type NewMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMessageResponse) Reset() {
	*x = NewMessageResponse{}
	mi := &file_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMessageResponse) ProtoMessage() {}

func (x *NewMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMessageResponse.ProtoReflect.Descriptor instead.
func (*NewMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *NewMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NewMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x13proto/gateway.proto\x12\agateway\"\x82\x01\n" +
	"\x11NewMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"F\n" +
	"\x12NewMessageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2a\n" +
	"\x0eGatewayService\x12O\n" +
	"\x10HandleNewMessage\x12\x1a.gateway.NewMessageRequest\x1a\x1b.gateway.NewMessageResponse\"\x000\x01B<Z:github.com/tdr-ticket_systems/kontur/service-gateway/protob\x06proto3"

var (
	file_proto_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_proto_rawDescData []byte
)

func file_proto_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_proto_rawDescData
}

var file_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gateway_proto_goTypes = []any{
	(*NewMessageRequest)(nil),  // 0: gateway.NewMessageRequest
	(*NewMessageResponse)(nil), // 1: gateway.NewMessageResponse
}
var file_proto_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.GatewayService.HandleNewMessage:input_type -> gateway.NewMessageRequest
	1, // 1: gateway.GatewayService.HandleNewMessage:output_type -> gateway.NewMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gateway_proto_init() }
func file_proto_gateway_proto_init() {
	if File_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_proto = out.File
	file_proto_gateway_proto_goTypes = nil
	file_proto_gateway_proto_depIdxs = nil
}
