apiVersion: v1
kind: Pod
metadata:
  name: temporal-proxy
  namespace: temporal
  labels:
    app: temporal-proxy
spec:
  containers:
  - name: socat
    image: alpine/socat
    args:
    - tcp-listen:7233,fork,reuseaddr
    - tcp-connect:host.docker.internal:7233
    ports:
    - containerPort: 7233 