// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/tickets.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to create a new ticket
type CreateTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VerticalId    string                 `protobuf:"bytes,1,opt,name=vertical_id,json=verticalId,proto3" json:"vertical_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Assign        string                 `protobuf:"bytes,3,opt,name=assign,proto3" json:"assign,omitempty"`
	SkillId       string                 `protobuf:"bytes,4,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketRequest) Reset() {
	*x = CreateTicketRequest{}
	mi := &file_proto_tickets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketRequest) ProtoMessage() {}

func (x *CreateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketRequest.ProtoReflect.Descriptor instead.
func (*CreateTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTicketRequest) GetVerticalId() string {
	if x != nil {
		return x.VerticalId
	}
	return ""
}

func (x *CreateTicketRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTicketRequest) GetAssign() string {
	if x != nil {
		return x.Assign
	}
	return ""
}

func (x *CreateTicketRequest) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

// Request to get a ticket
type GetTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketRequest) Reset() {
	*x = GetTicketRequest{}
	mi := &file_proto_tickets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketRequest) ProtoMessage() {}

func (x *GetTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketRequest.ProtoReflect.Descriptor instead.
func (*GetTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{1}
}

func (x *GetTicketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request to update a ticket
type UpdateTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VerticalId    string                 `protobuf:"bytes,2,opt,name=vertical_id,json=verticalId,proto3" json:"vertical_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Assign        string                 `protobuf:"bytes,4,opt,name=assign,proto3" json:"assign,omitempty"`
	SkillId       string                 `protobuf:"bytes,5,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketRequest) Reset() {
	*x = UpdateTicketRequest{}
	mi := &file_proto_tickets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketRequest) ProtoMessage() {}

func (x *UpdateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketRequest.ProtoReflect.Descriptor instead.
func (*UpdateTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTicketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTicketRequest) GetVerticalId() string {
	if x != nil {
		return x.VerticalId
	}
	return ""
}

func (x *UpdateTicketRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateTicketRequest) GetAssign() string {
	if x != nil {
		return x.Assign
	}
	return ""
}

func (x *UpdateTicketRequest) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

// Request to delete a ticket
type DeleteTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTicketRequest) Reset() {
	*x = DeleteTicketRequest{}
	mi := &file_proto_tickets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTicketRequest) ProtoMessage() {}

func (x *DeleteTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTicketRequest.ProtoReflect.Descriptor instead.
func (*DeleteTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTicketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response containing ticket data
type TicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VerticalId    string                 `protobuf:"bytes,2,opt,name=vertical_id,json=verticalId,proto3" json:"vertical_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Assign        string                 `protobuf:"bytes,4,opt,name=assign,proto3" json:"assign,omitempty"`
	SkillId       string                 `protobuf:"bytes,5,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketResponse) Reset() {
	*x = TicketResponse{}
	mi := &file_proto_tickets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketResponse) ProtoMessage() {}

func (x *TicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketResponse.ProtoReflect.Descriptor instead.
func (*TicketResponse) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{4}
}

func (x *TicketResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TicketResponse) GetVerticalId() string {
	if x != nil {
		return x.VerticalId
	}
	return ""
}

func (x *TicketResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TicketResponse) GetAssign() string {
	if x != nil {
		return x.Assign
	}
	return ""
}

func (x *TicketResponse) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *TicketResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TicketResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Response for delete operation
type DeleteTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTicketResponse) Reset() {
	*x = DeleteTicketResponse{}
	mi := &file_proto_tickets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTicketResponse) ProtoMessage() {}

func (x *DeleteTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tickets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTicketResponse.ProtoReflect.Descriptor instead.
func (*DeleteTicketResponse) Descriptor() ([]byte, []int) {
	return file_proto_tickets_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTicketResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_tickets_proto protoreflect.FileDescriptor

const file_proto_tickets_proto_rawDesc = "" +
	"\n" +
	"\x13proto/tickets.proto\x12\x06ticket\"\x82\x01\n" +
	"\x13CreateTicketRequest\x12\x1f\n" +
	"\vvertical_id\x18\x01 \x01(\tR\n" +
	"verticalId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06assign\x18\x03 \x01(\tR\x06assign\x12\x19\n" +
	"\bskill_id\x18\x04 \x01(\tR\askillId\"\"\n" +
	"\x10GetTicketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x92\x01\n" +
	"\x13UpdateTicketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vvertical_id\x18\x02 \x01(\tR\n" +
	"verticalId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06assign\x18\x04 \x01(\tR\x06assign\x12\x19\n" +
	"\bskill_id\x18\x05 \x01(\tR\askillId\"%\n" +
	"\x13DeleteTicketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xcb\x01\n" +
	"\x0eTicketResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vvertical_id\x18\x02 \x01(\tR\n" +
	"verticalId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06assign\x18\x04 \x01(\tR\x06assign\x12\x19\n" +
	"\bskill_id\x18\x05 \x01(\tR\askillId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"0\n" +
	"\x14DeleteTicketResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xab\x02\n" +
	"\rTicketService\x12E\n" +
	"\fCreateTicket\x12\x1b.ticket.CreateTicketRequest\x1a\x16.ticket.TicketResponse\"\x00\x12?\n" +
	"\tGetTicket\x12\x18.ticket.GetTicketRequest\x1a\x16.ticket.TicketResponse\"\x00\x12E\n" +
	"\fUpdateTicket\x12\x1b.ticket.UpdateTicketRequest\x1a\x16.ticket.TicketResponse\"\x00\x12K\n" +
	"\fDeleteTicket\x12\x1b.ticket.DeleteTicketRequest\x1a\x1c.ticket.DeleteTicketResponse\"\x00B?Z=github.com/aimustaev/service-tickets/internal/generated/protob\x06proto3"

var (
	file_proto_tickets_proto_rawDescOnce sync.Once
	file_proto_tickets_proto_rawDescData []byte
)

func file_proto_tickets_proto_rawDescGZIP() []byte {
	file_proto_tickets_proto_rawDescOnce.Do(func() {
		file_proto_tickets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tickets_proto_rawDesc), len(file_proto_tickets_proto_rawDesc)))
	})
	return file_proto_tickets_proto_rawDescData
}

var file_proto_tickets_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_tickets_proto_goTypes = []any{
	(*CreateTicketRequest)(nil),  // 0: ticket.CreateTicketRequest
	(*GetTicketRequest)(nil),     // 1: ticket.GetTicketRequest
	(*UpdateTicketRequest)(nil),  // 2: ticket.UpdateTicketRequest
	(*DeleteTicketRequest)(nil),  // 3: ticket.DeleteTicketRequest
	(*TicketResponse)(nil),       // 4: ticket.TicketResponse
	(*DeleteTicketResponse)(nil), // 5: ticket.DeleteTicketResponse
}
var file_proto_tickets_proto_depIdxs = []int32{
	0, // 0: ticket.TicketService.CreateTicket:input_type -> ticket.CreateTicketRequest
	1, // 1: ticket.TicketService.GetTicket:input_type -> ticket.GetTicketRequest
	2, // 2: ticket.TicketService.UpdateTicket:input_type -> ticket.UpdateTicketRequest
	3, // 3: ticket.TicketService.DeleteTicket:input_type -> ticket.DeleteTicketRequest
	4, // 4: ticket.TicketService.CreateTicket:output_type -> ticket.TicketResponse
	4, // 5: ticket.TicketService.GetTicket:output_type -> ticket.TicketResponse
	4, // 6: ticket.TicketService.UpdateTicket:output_type -> ticket.TicketResponse
	5, // 7: ticket.TicketService.DeleteTicket:output_type -> ticket.DeleteTicketResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tickets_proto_init() }
func file_proto_tickets_proto_init() {
	if File_proto_tickets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tickets_proto_rawDesc), len(file_proto_tickets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tickets_proto_goTypes,
		DependencyIndexes: file_proto_tickets_proto_depIdxs,
		MessageInfos:      file_proto_tickets_proto_msgTypes,
	}.Build()
	File_proto_tickets_proto = out.File
	file_proto_tickets_proto_goTypes = nil
	file_proto_tickets_proto_depIdxs = nil
}
