apiVersion: v1
kind: ConfigMap
metadata:
  name: service-workflow-config
  namespace: default
data:
  HTTP_HOST: "0.0.0.0"
  HTTP_PORT: "3000"
  TEMPORAL_HOST: "host.docker.internal"
  TEMPORAL_PORT: "7233"
  TEMPORAL_NAMESPACE: "default" 
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_TOPIC: "workflow-events"
  TICKET_SERVICE_HOST: "service-tickets"
  TICKET_SERVICE_PORT: "50051"
  