apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-workflow-consumer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-workflow-consumer
  template:
    metadata:
      labels:
        app: service-workflow-consumer
    spec:
      containers:
      - name: consumer
        image: airat139/service-workflow:8
        imagePullPolicy: Always
        command: ["/app/consumer"]
        envFrom:
        - configMapRef:
            name: service-workflow-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi" 