apiVersion: v1
kind: Service
metadata:
  name: service-workflow-service
  namespace: default
spec:
  selector:
    app: service-workflow-service
  ports:
  - port: 80
    targetPort: 3002
  type: ClusterIP 